### ISSUE TITLE
Issue #90 closed but I continue to get the same output error in modis_mosaic.py

### ISSUE THREAD

**Issue by Maria-da-Conceicao-Pereira** [lucadelu/pyModis#94]
Dear @lucadelu and @romulogoncalves,

In issue #90 @romulogoncalves reported an error, related with the output format, when applying the script modis_mosaic.py to obtain a mosaic of some .hdf MODIS images, in GTiff format. @romulogoncalves tested the command in 2 different GDAL versions, including a recent one, and obtained in both cases the same error, suggesting 2 small corrections in the code, which @lucadelu implemented in commit fe9380d. Afterwards @romulogoncalves patched the code of the package, installed it with the corrections, and it worked. The issue was considered closed.

The problem is that probably those corrections are not implemented in the latest version of pyModis available to common users. I'm using pyModis 2.0.6, installed it with pip, and I get exactly the same output format error as @romulogoncalves in issue #90, when trying to mosaic a series of MODIS burnt area product tiles from Africa:

modis_mosaic.py -f GTiff -o Mosaic_Test_4.tif Mosaic_Test_4.txt
Traceback (most recent call last):
File "C:\Python27\ArcGIS10.2\Scripts\modis_mosaic.py", line 150, in (module) main()
File "C:\Python27\ArcGIS10.2\Scripts\modis_mosaic.py", line 144, in main
modisOgg.run(output)
File "C:\Python27\ArcGIS10.2\Lib\site-packages\pymodis\convertmodis_gdal.py", line 616, in run
"created".format(name=self.out))
AttributeError: createMosaicGDAL instance has no attribute 'out'

Can you please help me? I don't know how to patch code, I'm not a programmer... And I suppose I can't simply change the code directly in the script... How can I obtain a version of the script and/or the package with these corrections implemented? I have to confess I feel a bit desperate because I've been busy with the downloading and preprocessing of my MODIS images for many weeks (first I tried R, which I had used in the past, but my MODIS product of interest is new, and Modis-R, a dedicated R package for MODIS, is not yet prepared for this new product; I then discovered pyModis and decided to switch to it, having to get familiar with python, which is rather new to me...). So, if you can help me I'd be really, really grateful...!

Finally, I also would like to congratulate @lucadelu and all involved for the creation, development and continuous update of package pyModis!

Greetings and I hope to hear from you soon!
Maria Pereira

**Comment by lucadelu** [comment]
@Maria-da-Conceicao-Pereira sorry the problem was fixed long time ago, but I never release new version. I will do it in the next 4 hours.

best regards

**Comment by Maria-da-Conceicao-Pereira** [comment]
Dear @lucadelu,

thank you for the prompt reply and clarification!

I would like to kindly ask you to post something here when the new and corrected version is made available to users (I've just checked and still see no changes in the versions available, both in pyModis 2.0.6 documentation and Python Package Index), since I'm at this moment completely dependent on this to move on with my work.

Thank you very much!!

PS - By the way, in case you still want to include the correction of a similar error in the new version, here goes what I obtained:

When trying to use the same script to mosaic a series of MODIS tiles using a virtual file in GDAL:

modis_mosaic.py -v -o Mosaic_Test_4.vrt Mosaic_Test_4.txt
Traceback (most recent call last):
File "C:\Python27\ArcGIS10.2\Scripts\modis_mosaic.py", line 150, in (module) main()
File "C:\Python27\ArcGIS10.2\Scripts\modis_mosaic.py", line 142, in main
modisOgg.write_vrt(output)
File "C:\Python27\ArcGIS10.2\Lib\site-packages\pymodis\convertmodis_gdal.py", line 717, in write_vrt
"created".format(name=self.out))
AttributeError: createMosaicGDAL instance has no attribute 'out'

**Comment by lucadelu** [comment]
@Maria-da-Conceicao-Pereira released version 2.0.7

**Comment by Maria-da-Conceicao-Pereira** [comment]
THANK YOU very much!

**Comment by Maria-da-Conceicao-Pereira** [comment]
THANK YOU VERY MUCH!

Maria Pereira | PhD Candidate
Wageningen University
Laboratory of Geo-information Science and Remote Sensing (www.grs.wur.nl/UK)
maria2.pereira@wur.nl<mailto:maria2.pereira@wur.nl> | T +31(0)317481697 | M +31(0)637405947
